### PR TITLE
[basic-updates] for gem

### PR DESCRIPTION
**Pull request by dvmonroe**
Change license from Apache to MIT
Add rubocop for development
Add changelog
-  auto generated by changelog gem

Update Readme
-  removed comments about deploying

Reorganize gemspec
-  moved dev and test dependencies to gemfile
-  kept main dev dependencies but moved around

### CODE REVIEW

**Comment by kkirsche** [comment]
Not interested in changing the license.  Even if I was it's not as simple as a pull request as other contributors have to agree to re-licensing their code.

**Comment by dvmonroe** [comment]
Just out of curiosity why are you intent on making it apache? 
I'm also not seeing any other contributors at this point? Am i wrong about that?

you're also missing the year and owner name: 

```
Copyright {yyyy} {name of copyright owner}
```

questionable if it's even legally binding as is.

**Comment by kkirsche** [comment]
Yes, there are two others contributors in the repository.

**Comment by dvmonroe** [comment]
Ok cool - sry for missing that.  Are you interested in more contributions/contributors and would you accept this PR without a license change?

**Pull request closed without merging**
